### ISSUE TITLE
Sup, problem with warzone 2

### ISSUE THREAD

**Issue by lemonekq** [JayXTQ/AtlasGuides#1]
Script giving the version 789.
`reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v UBR /t REG_DWORD /d 789 /f`

But the working one is 790
`reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v UBR /t REG_DWORD /d 790 /f`

also script is too spaghetti lol, you could make that in one file

**Comment by JayXTQ** [comment]
Will update soon, thanks. And also sometimes powershell doesn’t want to work on some systems which is why it is 2 files

**Comment by lemonekq** [comment]
change bitly to current repo there. thanks for fixing tommorow

**Comment by JayXTQ** [comment]
I don't understand what you mean by change bitly? The bitly file leads directly to the Discord file. It's just easier to reference.

**Comment by JayXTQ** [comment]
Just understood what you meant, updated the code like you asked.
